// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cyberguru1/stage-two/ent/organisation"
	"github.com/cyberguru1/stage-two/ent/predicate"
	"github.com/cyberguru1/stage-two/ent/user"
	"github.com/google/uuid"
)

// OrganisationUpdate is the builder for updating Organisation entities.
type OrganisationUpdate struct {
	config
	hooks    []Hook
	mutation *OrganisationMutation
}

// Where appends a list predicates to the OrganisationUpdate builder.
func (ou *OrganisationUpdate) Where(ps ...predicate.Organisation) *OrganisationUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetOrgid sets the "orgid" field.
func (ou *OrganisationUpdate) SetOrgid(u uuid.UUID) *OrganisationUpdate {
	ou.mutation.SetOrgid(u)
	return ou
}

// SetNillableOrgid sets the "orgid" field if the given value is not nil.
func (ou *OrganisationUpdate) SetNillableOrgid(u *uuid.UUID) *OrganisationUpdate {
	if u != nil {
		ou.SetOrgid(*u)
	}
	return ou
}

// SetName sets the "name" field.
func (ou *OrganisationUpdate) SetName(s string) *OrganisationUpdate {
	ou.mutation.SetName(s)
	return ou
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ou *OrganisationUpdate) SetNillableName(s *string) *OrganisationUpdate {
	if s != nil {
		ou.SetName(*s)
	}
	return ou
}

// SetDescription sets the "description" field.
func (ou *OrganisationUpdate) SetDescription(s string) *OrganisationUpdate {
	ou.mutation.SetDescription(s)
	return ou
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ou *OrganisationUpdate) SetNillableDescription(s *string) *OrganisationUpdate {
	if s != nil {
		ou.SetDescription(*s)
	}
	return ou
}

// ClearDescription clears the value of the "description" field.
func (ou *OrganisationUpdate) ClearDescription() *OrganisationUpdate {
	ou.mutation.ClearDescription()
	return ou
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (ou *OrganisationUpdate) SetUsersID(id int) *OrganisationUpdate {
	ou.mutation.SetUsersID(id)
	return ou
}

// SetNillableUsersID sets the "users" edge to the User entity by ID if the given value is not nil.
func (ou *OrganisationUpdate) SetNillableUsersID(id *int) *OrganisationUpdate {
	if id != nil {
		ou = ou.SetUsersID(*id)
	}
	return ou
}

// SetUsers sets the "users" edge to the User entity.
func (ou *OrganisationUpdate) SetUsers(u *User) *OrganisationUpdate {
	return ou.SetUsersID(u.ID)
}

// Mutation returns the OrganisationMutation object of the builder.
func (ou *OrganisationUpdate) Mutation() *OrganisationMutation {
	return ou.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (ou *OrganisationUpdate) ClearUsers() *OrganisationUpdate {
	ou.mutation.ClearUsers()
	return ou
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OrganisationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OrganisationUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OrganisationUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OrganisationUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OrganisationUpdate) check() error {
	if v, ok := ou.mutation.Name(); ok {
		if err := organisation.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Organisation.name": %w`, err)}
		}
	}
	return nil
}

func (ou *OrganisationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(organisation.Table, organisation.Columns, sqlgraph.NewFieldSpec(organisation.FieldID, field.TypeInt))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.Orgid(); ok {
		_spec.SetField(organisation.FieldOrgid, field.TypeUUID, value)
	}
	if value, ok := ou.mutation.Name(); ok {
		_spec.SetField(organisation.FieldName, field.TypeString, value)
	}
	if value, ok := ou.mutation.Description(); ok {
		_spec.SetField(organisation.FieldDescription, field.TypeString, value)
	}
	if ou.mutation.DescriptionCleared() {
		_spec.ClearField(organisation.FieldDescription, field.TypeString)
	}
	if ou.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organisation.UsersTable,
			Columns: []string{organisation.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organisation.UsersTable,
			Columns: []string{organisation.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organisation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OrganisationUpdateOne is the builder for updating a single Organisation entity.
type OrganisationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrganisationMutation
}

// SetOrgid sets the "orgid" field.
func (ouo *OrganisationUpdateOne) SetOrgid(u uuid.UUID) *OrganisationUpdateOne {
	ouo.mutation.SetOrgid(u)
	return ouo
}

// SetNillableOrgid sets the "orgid" field if the given value is not nil.
func (ouo *OrganisationUpdateOne) SetNillableOrgid(u *uuid.UUID) *OrganisationUpdateOne {
	if u != nil {
		ouo.SetOrgid(*u)
	}
	return ouo
}

// SetName sets the "name" field.
func (ouo *OrganisationUpdateOne) SetName(s string) *OrganisationUpdateOne {
	ouo.mutation.SetName(s)
	return ouo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ouo *OrganisationUpdateOne) SetNillableName(s *string) *OrganisationUpdateOne {
	if s != nil {
		ouo.SetName(*s)
	}
	return ouo
}

// SetDescription sets the "description" field.
func (ouo *OrganisationUpdateOne) SetDescription(s string) *OrganisationUpdateOne {
	ouo.mutation.SetDescription(s)
	return ouo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ouo *OrganisationUpdateOne) SetNillableDescription(s *string) *OrganisationUpdateOne {
	if s != nil {
		ouo.SetDescription(*s)
	}
	return ouo
}

// ClearDescription clears the value of the "description" field.
func (ouo *OrganisationUpdateOne) ClearDescription() *OrganisationUpdateOne {
	ouo.mutation.ClearDescription()
	return ouo
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (ouo *OrganisationUpdateOne) SetUsersID(id int) *OrganisationUpdateOne {
	ouo.mutation.SetUsersID(id)
	return ouo
}

// SetNillableUsersID sets the "users" edge to the User entity by ID if the given value is not nil.
func (ouo *OrganisationUpdateOne) SetNillableUsersID(id *int) *OrganisationUpdateOne {
	if id != nil {
		ouo = ouo.SetUsersID(*id)
	}
	return ouo
}

// SetUsers sets the "users" edge to the User entity.
func (ouo *OrganisationUpdateOne) SetUsers(u *User) *OrganisationUpdateOne {
	return ouo.SetUsersID(u.ID)
}

// Mutation returns the OrganisationMutation object of the builder.
func (ouo *OrganisationUpdateOne) Mutation() *OrganisationMutation {
	return ouo.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (ouo *OrganisationUpdateOne) ClearUsers() *OrganisationUpdateOne {
	ouo.mutation.ClearUsers()
	return ouo
}

// Where appends a list predicates to the OrganisationUpdate builder.
func (ouo *OrganisationUpdateOne) Where(ps ...predicate.Organisation) *OrganisationUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OrganisationUpdateOne) Select(field string, fields ...string) *OrganisationUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Organisation entity.
func (ouo *OrganisationUpdateOne) Save(ctx context.Context) (*Organisation, error) {
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OrganisationUpdateOne) SaveX(ctx context.Context) *Organisation {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OrganisationUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OrganisationUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OrganisationUpdateOne) check() error {
	if v, ok := ouo.mutation.Name(); ok {
		if err := organisation.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Organisation.name": %w`, err)}
		}
	}
	return nil
}

func (ouo *OrganisationUpdateOne) sqlSave(ctx context.Context) (_node *Organisation, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organisation.Table, organisation.Columns, sqlgraph.NewFieldSpec(organisation.FieldID, field.TypeInt))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Organisation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organisation.FieldID)
		for _, f := range fields {
			if !organisation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != organisation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.Orgid(); ok {
		_spec.SetField(organisation.FieldOrgid, field.TypeUUID, value)
	}
	if value, ok := ouo.mutation.Name(); ok {
		_spec.SetField(organisation.FieldName, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Description(); ok {
		_spec.SetField(organisation.FieldDescription, field.TypeString, value)
	}
	if ouo.mutation.DescriptionCleared() {
		_spec.ClearField(organisation.FieldDescription, field.TypeString)
	}
	if ouo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organisation.UsersTable,
			Columns: []string{organisation.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organisation.UsersTable,
			Columns: []string{organisation.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Organisation{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organisation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
