// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cyberguru1/stage-two/ent/organisation"
	"github.com/cyberguru1/stage-two/ent/user"
	"github.com/google/uuid"
)

// OrganisationCreate is the builder for creating a Organisation entity.
type OrganisationCreate struct {
	config
	mutation *OrganisationMutation
	hooks    []Hook
}

// SetOrgid sets the "orgid" field.
func (oc *OrganisationCreate) SetOrgid(u uuid.UUID) *OrganisationCreate {
	oc.mutation.SetOrgid(u)
	return oc
}

// SetNillableOrgid sets the "orgid" field if the given value is not nil.
func (oc *OrganisationCreate) SetNillableOrgid(u *uuid.UUID) *OrganisationCreate {
	if u != nil {
		oc.SetOrgid(*u)
	}
	return oc
}

// SetName sets the "name" field.
func (oc *OrganisationCreate) SetName(s string) *OrganisationCreate {
	oc.mutation.SetName(s)
	return oc
}

// SetDescription sets the "description" field.
func (oc *OrganisationCreate) SetDescription(s string) *OrganisationCreate {
	oc.mutation.SetDescription(s)
	return oc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (oc *OrganisationCreate) SetNillableDescription(s *string) *OrganisationCreate {
	if s != nil {
		oc.SetDescription(*s)
	}
	return oc
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (oc *OrganisationCreate) SetUsersID(id int) *OrganisationCreate {
	oc.mutation.SetUsersID(id)
	return oc
}

// SetNillableUsersID sets the "users" edge to the User entity by ID if the given value is not nil.
func (oc *OrganisationCreate) SetNillableUsersID(id *int) *OrganisationCreate {
	if id != nil {
		oc = oc.SetUsersID(*id)
	}
	return oc
}

// SetUsers sets the "users" edge to the User entity.
func (oc *OrganisationCreate) SetUsers(u *User) *OrganisationCreate {
	return oc.SetUsersID(u.ID)
}

// Mutation returns the OrganisationMutation object of the builder.
func (oc *OrganisationCreate) Mutation() *OrganisationMutation {
	return oc.mutation
}

// Save creates the Organisation in the database.
func (oc *OrganisationCreate) Save(ctx context.Context) (*Organisation, error) {
	oc.defaults()
	return withHooks(ctx, oc.sqlSave, oc.mutation, oc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OrganisationCreate) SaveX(ctx context.Context) *Organisation {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *OrganisationCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *OrganisationCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oc *OrganisationCreate) defaults() {
	if _, ok := oc.mutation.Orgid(); !ok {
		v := organisation.DefaultOrgid()
		oc.mutation.SetOrgid(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oc *OrganisationCreate) check() error {
	if _, ok := oc.mutation.Orgid(); !ok {
		return &ValidationError{Name: "orgid", err: errors.New(`ent: missing required field "Organisation.orgid"`)}
	}
	if _, ok := oc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Organisation.name"`)}
	}
	if v, ok := oc.mutation.Name(); ok {
		if err := organisation.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Organisation.name": %w`, err)}
		}
	}
	return nil
}

func (oc *OrganisationCreate) sqlSave(ctx context.Context) (*Organisation, error) {
	if err := oc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	oc.mutation.id = &_node.ID
	oc.mutation.done = true
	return _node, nil
}

func (oc *OrganisationCreate) createSpec() (*Organisation, *sqlgraph.CreateSpec) {
	var (
		_node = &Organisation{config: oc.config}
		_spec = sqlgraph.NewCreateSpec(organisation.Table, sqlgraph.NewFieldSpec(organisation.FieldID, field.TypeInt))
	)
	if value, ok := oc.mutation.Orgid(); ok {
		_spec.SetField(organisation.FieldOrgid, field.TypeUUID, value)
		_node.Orgid = value
	}
	if value, ok := oc.mutation.Name(); ok {
		_spec.SetField(organisation.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := oc.mutation.Description(); ok {
		_spec.SetField(organisation.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := oc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organisation.UsersTable,
			Columns: []string{organisation.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_organisations = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrganisationCreateBulk is the builder for creating many Organisation entities in bulk.
type OrganisationCreateBulk struct {
	config
	err      error
	builders []*OrganisationCreate
}

// Save creates the Organisation entities in the database.
func (ocb *OrganisationCreateBulk) Save(ctx context.Context) ([]*Organisation, error) {
	if ocb.err != nil {
		return nil, ocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*Organisation, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrganisationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *OrganisationCreateBulk) SaveX(ctx context.Context) []*Organisation {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *OrganisationCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *OrganisationCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}
